/*
 Navicat Premium Data Transfer

 Source Server         : Mysql8-基线库
 Source Server Type    : MySQL
 Source Server Version : 80032 (8.0.32)
 Source Host           : 192.168.1.199:3306
 Source Schema         : lsgz_s

 Target Server Type    : MySQL
 Target Server Version : 80032 (8.0.32)
 File Encoding         : 65001

 Date: 15/12/2023 10:05:45
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for sys_flow
-- ----------------------------
DROP TABLE IF EXISTS `sys_flow`;
CREATE TABLE `sys_flow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '审批类别',
  `code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '审批编号',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '审批名称',
  `fetch_field_definition_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '取数字段定义',
  `default_fetch_field_json` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '默认取数字段',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态  0-禁用；1-启用',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标识：0-未删除 ；1-已删除',
  `i18n_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '国际化json',
  `sort` int DEFAULT '0' COMMENT '排序',
  `parent_id` bigint DEFAULT '0' COMMENT '父级id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_code` (`code`) USING BTREE,
  KEY `idx_category` (`category`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1647862228147126328 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程表';

-- ----------------------------
-- Records of sys_flow
-- ----------------------------
BEGIN;
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10001, 'account', 'open_account', '账户审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Account examine and approve\",\"zh_cn\":\"账户审批\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10002, 'budget', 'budget_adjust', '计划调整审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Plan Adjustment examine and approve\",\"zh_cn\":\"计划调整审批\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10003, 'budget', 'budget_summary', '计划汇总审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Plan Summary examine and approve\",\"zh_cn\":\"计划汇总审批\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10004, 'budget', 'budget_wave', '计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"plan examine and approve\",\"zh_cn\":\"计划审批\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10005, 'budget', 'program_budget', '项目计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Project plan examine and approve\",\"zh_cn\":\"项目计划审批\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10006, 'cash_pool', 'fund_collection', '归集审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Collection examine and approve\",\"zh_cn\":\"归集审批\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10007, 'cash_pool', 'fund_transfer', '下拨审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"allocation examine and approve\",\"zh_cn\":\"下拨审批\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10008, 'cash_pool', 'fund_transfer_rule', '内部往来规则审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Internal transactions Rules examine and approve\",\"zh_cn\":\"内部往来规则审批\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10009, 'cash_pool', 'internal_transfer', '调拨审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"transfer examine and approve\",\"zh_cn\":\"调拨审批\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10010, 'data_source', 'purchage_apply', '采购审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Purchase examine and approve\",\"zh_cn\":\"采购审批\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10011, 'data_source', 'sale_contract', '销售审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Sales examine and approve\",\"zh_cn\":\"销售审批\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10012, 'finance', 'bill_info_approve', '收票登记审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 14:12:58', 1, 1, '{\"en_us\":\"Invoice registration examine and approve\",\"zh_cn\":\"收票登记审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10013, 'data_source', 'bill_pool_finance', '池融资', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Bill Pool Financing \",\"zh_cn\":\"池融资\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10014, 'data_source', 'bill_pool_limit_adjust', '池额度', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Pool quota\",\"zh_cn\":\"池额度\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10015, 'finance', 'capital_invest', '投资审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"investment examine and approve\",\"zh_cn\":\"投资审批\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10016, 'finance', 'change_deposit_approve', '定期存款受限变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10017, 'finance', 'confirm_deposit_earnings', '定期存款确认收益审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10018, 'finance', 'confirm_financial_earnings', '理财确认收益审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10019, 'finance', 'credit_change', '授信变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10020, 'data_source', 'deposit_transfer', '池保证金划转', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Pool Margin Transfer\",\"zh_cn\":\"池保证金划转\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10021, 'finance', 'direct_finance_contract', '发行审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Release examine and approve\",\"zh_cn\":\"发行审批\"}', 17, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10022, 'finance', 'direct_finance_issue', '登记审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Registration examine and approve\",\"zh_cn\":\"登记审批\"}', 18, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10023, 'finance', 'endorse_bill', '背书审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 14:12:58', 1, 1, '{\"en_us\":\"endorsement examine and approve\",\"zh_cn\":\"背书审批\"}', 10, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10024, 'finance', 'factoring_finance', '保理审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"factoring examine and approve\",\"zh_cn\":\"保理审批\"}', 19, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10025, 'finance', 'finance_change', '变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Change examine and approve\",\"zh_cn\":\"变更审批\"}', 9, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10026, 'finance', 'finance_contract', '融资审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:45:16', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10027, 'finance', 'finance_credit', '授信审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10028, 'finance', 'finance_fee', '融资费用', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:55', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Financing charges\",\"zh_cn\":\"融资费用\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10029, 'finance', 'finance_loan_contract_draw_plan', '融资合同提款审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:45:16', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10030, 'finance', 'finance_plan', '融资计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Financing Plan examine and approve\",\"zh_cn\":\"融资计划审批\"}', 6, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10031, 'finance', 'financial_apply', '理财审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10032, 'finance', 'financial_contract_change', '理财变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10033, 'finance', 'financial_planning', '理财计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10034, 'finance', 'financial_purchase_finance', '理财申购审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10035, 'finance', 'financial_redemption', '理财赎回审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:15', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10036, 'finance', 'financing_deposit_redemption', '定期存款赎回/支取审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10037, 'finance', 'financing_regular_deposit_append', '定期存款新增', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10038, 'finance', 'guarantee_contract', '担保合同审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Guarantee contract examine and approve\",\"zh_cn\":\"担保合同审批\"}', 21, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10039, 'finance', 'inner_processing_finance', '内部往来审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:45:16', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10040, 'finance', 'issue_bill', '出票审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 14:12:58', 1, 1, '{\"en_us\":\"ticket examine and approve\",\"zh_cn\":\"出票审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10041, 'finance', 'open_guarantee_letter', '保函开立审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 14:14:58', 1, 1, '{\"en_us\":\"Letter of guarantee issuance examine and approve\",\"zh_cn\":\"保函开立审批\"}', 28, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10042, 'finance', 'operate_bill_pool', '票据池审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 14:12:58', 1, 1, '{\"en_us\":\"The approval for Bill Pool\",\"zh_cn\":\"票据池审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10043, 'finance', 'redemption_foreign_finance', '赎回型结售汇审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:24', 1, 0, '{\"en_us\":\"Redemption-type foreign exchange settlement and sale examine and approve\",\"zh_cn\":\"赎回型结售汇审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10044, 'finance', 'regular_deposit_redemption', '定期存款赎回审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10045, 'finance', 'regular_deposit_transfer', '定期存款转让审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10046, 'finance', 'repay_apply', '还款审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10047, 'finance', 'repay_loan_extension', '展期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10048, 'finance', 'repay_plan', '还款计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:41:14', 1, 1, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10049, 'finance', 'repeal_bill', '撤票审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 14:12:58', 1, 1, '{\"en_us\":\"Withdrawal examine and approve\",\"zh_cn\":\"撤票审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10050, 'finance', 'reverse_factoring_finance', '反向保理审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Reverse factoring examine and approve\",\"zh_cn\":\"反向保理审批\"}', 20, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10051, 'finance', 'shareholder_dividend', '分红审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Dividend examine and approve\",\"zh_cn\":\"分红审批\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10052, 'finance', 'single_foreignCurrency_finance', '单笔结售汇', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Single settlement and sale of foreign exchange\",\"zh_cn\":\"单笔结售汇\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10053, 'finance', 'use_finance_credit', '用信审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 1, NULL, 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10054, 'global', 'cbft_pay', '跨境支付审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Cross-border payment examine and approve\",\"zh_cn\":\"跨境支付审批\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10055, 'global', 'exposure_operate', '敞口风险操作审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Exposure risk operation examine and approve\",\"zh_cn\":\"敞口风险操作审批\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10056, 'global', 'global_pay', '境外支付审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Overseas payment examine and approve\",\"zh_cn\":\"境外支付审批\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10057, 'global', 'lc_issue_apply', '开证审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Issuance examine and approve\",\"zh_cn\":\"开证审批\"}', 99, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10058, 'finance', 'lc_operate_apply', '信用证融资审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Letter of credit financing examine and approve\",\"zh_cn\":\"信用证融资审批\"}', 16, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10059, 'accounting_center', 'balance_adjustment', '余额调节表审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Balance Reconciliation examine and approve\",\"zh_cn\":\"余额调节表审批\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10060, 'cash_pool', 'bank_allocation_in', '银行户调拨拨入（应付）', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Bank account transfer in (payable)\",\"zh_cn\":\"银行户调拨拨入（应付）\"}', 6, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10061, 'cash_pool', 'bank_allocation_in_merge', '银行调拨拨入合并审批（应付）', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Bank transfer and transfer in consolidated examine and approve (payable)\",\"zh_cn\":\"银行调拨拨入合并审批（应付）\"}', 7, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10062, 'cash_pool', 'bank_allocation_out', '银行户调拨拨出（应付）', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Bank account transfer out (payable)\",\"zh_cn\":\"银行户调拨拨出（应付）\"}', 8, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10063, 'cash_pool', 'bank_allocation_out_merge', '银行调拨拨出合并审批（应付）', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Bank transfer and transfer out consolidated examine and approve (payable)\",\"zh_cn\":\"银行调拨拨出合并审批（应付）\"}', 9, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10064, 'cash_pool', 'bank_transfer', '银行户调拨', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"bank account transfer\",\"zh_cn\":\"银行户调拨\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10065, 'payment', 'bank_transfer_out', '银行户调拨-拨出', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Bank Account Transfer in - transfer out\",\"zh_cn\":\"银行户调拨-拨出\"}', 10, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10066, 'payment', 'batch_pay_docking', '批量支付对接', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Batch payment docking\",\"zh_cn\":\"批量支付对接\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10067, 'payment', 'foreign_payment', '支付审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"approval of payment \",\"zh_cn\":\"支付审批\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10068, 'payment', 'group_agent_payment', '代理支付', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Agency payment\",\"zh_cn\":\"代理支付\"}', 10, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10069, 'payment', 'payable_audit', '应付审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Payable examine and approve\",\"zh_cn\":\"应付审批\"}', 7, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10070, 'payment', 'payable_merge_audit', '应付合并审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Payable Consolidation examine and approve\",\"zh_cn\":\"应付合并审批\"}', 8, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10071, 'payment', 'payment_exception', '异常审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"abnormal examine and approve \",\"zh_cn\":\"异常审批\"}', 6, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10072, 'payment', 'payroll', '工资代发', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Agency salary payment\",\"zh_cn\":\"工资代发\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10073, 'payment', 'redemption_foreignCurrency_finance', '赎回型结售汇审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Redemption-type foreign exchange settlement and sale examine and approve\",\"zh_cn\":\"赎回型结售汇审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10074, 'accounting_center', 'subject_detail_check', '科目明细对账审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:26', 1, 0, '{\"en_us\":\"Account Detail Reconciliation examine and approve\",\"zh_cn\":\"科目明细对账审批\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10075, 'payment', 'withdrawal_of_claim', '收款认领撤回', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:34:56', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Collection claim withdrawal\",\"zh_cn\":\"收款认领撤回\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10077, 'payment', 'foreign_batch_distribution', '批量支付', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:35:26', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Batch payment\",\"zh_cn\":\"批量支付\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10078, 'payment', 'group_salary_agent', '代理工资代发', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:35:26', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Agency salary payment\",\"zh_cn\":\"代理工资代发\"}', 12, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10079, 'payment', 'group_batch_distribution_agent', '代理批量支付', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:35:26', '2023-11-21 13:46:25', 1, 0, '{\"en_us\":\"Agent batch payment\",\"zh_cn\":\"代理批量支付\"}', 11, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10080, 'payment', 'pay_transaction_again', '重新支付', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-07-14 20:35:26', '2023-11-21 13:46:25', 0, 0, '{\"en_us\":\"Re-pay\",\"zh_cn\":\"重新支付\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10081, 'cash_assets', 'new_approval_virtual_accounts', '存款申购申请', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:15:42', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款申购申请\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10082, 'cash_assets', 'regular_deposit_append', '存款新增', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款新增\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10083, 'cash_assets', 'deposit_full_transfer', '存款转让', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款转让\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10084, 'cash_assets', 'deposit_withdrawal', '存款支取', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款支取\"}', 8, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10085, 'cash_assets', 'deposit_limited', '存款受限', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款受限\"}', 6, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10086, 'cash_assets', 'deposit_survival', '存款存续', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款存续\"}', 7, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10087, 'cash_assets', 'deposit_change', '存款变更', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款变更\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10088, 'bill', 'buyer_letter_register', '买方信用证-开立登记-审批类型', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 13:46:26', 0, 0, '{\"en_us\":\"Buyer`s Letter of Credit - Opening Registration - examine and approve\",\"zh_cn\":\"买方信用证-开立登记-审批\"}', 6, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10089, 'bill', 'seller_letter_register', '卖方信用证-收证登记-审批类型', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 13:46:26', 0, 0, '{\"en_us\":\"Seller`s letter of credit - receipt registration - examine and approve\",\"zh_cn\":\"卖方信用证-收证登记-审批\"}', 8, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10090, 'bill', 'buyer_letter_apply', '买方信用证-开立申请-审批类型', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 13:46:26', 0, 0, '{\"en_us\":\"Buyer`s Letter of Credit - Opening Application - examine and approve\",\"zh_cn\":\"买方信用证-开立申请-审批\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10091, 'bill', 'seller_letter_apply', '卖方信用证-收证申请-审批类型', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 13:46:26', 0, 0, '{\"en_us\":\"Seller`s Letter of Credit - Application for Receipt - examine and approve\",\"zh_cn\":\"卖方信用证-收证申请-审批\"}', 7, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10092, 'bill', 'sign_bill', '票据签收', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:17:25', 0, 0, '{\"en_us\":\"Bill signing and examine and approve\",\"zh_cn\":\"票据签收审批\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10093, 'bill', 'bill_endorse_apply', '票据背书', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:17:25', 0, 0, '{\"en_us\":\"Endorsement Approval\",\"zh_cn\":\"背书审批\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10094, 'bill', 'bill_payable_endorse_apply', '关联应付单票据背书申请审批类型', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:12:58', 0, 1, '{\"en_us\":\"examine and approve of application for endorsement of related SPA bills\",\"zh_cn\":\"关联应付单票据背书申请审批\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (10095, 'payment', 'bis_mixture_docking', '混合支付对接', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:15:40', '2023-11-21 14:15:40', 0, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (20081, 'cash_assets', 'new_financial_redemption', '理财赎回', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"理财赎回\"}', 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (20082, 'cash_assets', 'new_financial_purchase', '理财申购', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"理财申购\"}', 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (20086, 'cash_assets', 'apply_approval_financial', '理财申购申请', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"理财申购申请\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (20087, 'cash_assets', 'new_approval_financial', '理财新增', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-09-14 10:18:17', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"理财新增\"}', 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (66220, 'cash_pool', 'new_inner_finance_borrow', '往来借款-借入新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 11, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (66320, 'finance', 'new_finance_credit_usage_apply', '用信申请-申请用信审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 22, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (66398, 'cash_pool', 'new_loan_inter_draw', '往来借款-提款审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 16, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100001, 'finance', 'new_repay_contract_prepayment', '待还合同-提前还款审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:14:58', 1, 0, NULL, 14, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100002, 'finance', 'new_repay_contract_exhibition', '待还合同-展期还款审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:14:58', 1, 0, NULL, 13, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100003, 'finance', 'new_repay_contract_delay', '待还合同-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:14:58', 1, 0, NULL, 12, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100004, 'finance', 'new_repayment_schedule', '待还合同-还款计划审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:14:58', 1, 0, NULL, 10, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100005, 'accounting_center', 'subject_detail_recon_recall', '科目明细对账撤回审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 13:41:14', '2023-11-21 13:46:26', 0, 0, NULL, 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100006, 'revenue_plan', 'revenue_plan_submit_approval', '收支计划填报审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 13:41:14', '2023-11-21 13:46:26', 1, 0, NULL, 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100007, 'revenue_plan', 'revenue_plan_collect_approval', '收支计划汇总审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 13:41:14', '2023-11-21 13:46:26', 1, 0, NULL, 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100008, 'finance', 'new_repay_contract_terminate', '待还合同-终止审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:14:58', 1, 0, NULL, 11, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100140, 'finance', 'new_finance_loan_stop', '融资合同-终止审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 4, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (100141, 'finance', 'new_finance_loan_renewal', '融资合同-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 3, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000137, 'cash_pool', 'new_inner_change_finance', '往来借款-变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 13, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000138, 'cash_pool', 'new_inner_stop_finance', '往来借款-终止审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 14, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000139, 'cash_pool', 'new_inner_renewal_finance', '往来借款-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 13:41:14', '2023-11-21 14:14:58', 1, 0, NULL, 15, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000140, 'account', 'bank_consociation_add', '合作银行新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-11-19 17:19:02', '2023-11-21 13:46:26', 1, 0, NULL, 9, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000142, 'account', 'bank_consociation_renewal', '合作银行续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-11-19 17:19:02', '2023-11-21 13:46:26', 1, 0, NULL, 11, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000143, 'account', 'internal_on_the_way_balance', '内部户在途余额异常审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 13:41:14', '2023-11-21 13:46:26', 0, 0, NULL, 12, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000144, 'cash_assets', 'interest_settlement', '投资结息', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 13:45:16', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"投资结息\"}', 5, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000145, 'finance', 'new_repay_contract_submit', '待还合同-新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}} ', '{\"org\": \"userOrg\"}', '2023-11-21 13:45:16', '2023-11-21 14:14:58', 1, 0, NULL, 15, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1000146, 'cash_assets', 'deposit_purchase', '存款申购', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2022-06-28 20:16:57', '2023-11-21 14:16:02', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"存款申购\"}', 7, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1633734715401818114, 'finance', 'new_repay_contract_change', '待还合同-变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:12:58', '2023-11-21 14:12:58', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1633734715401818115, 'payment', 'repair_payment_bill', '应付单配票审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:13:01', '2023-11-21 14:13:01', 0, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1633734715401818116, 'payment', 'negotiable_payment_bill', '应付单背书审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:13:01', '2023-11-21 14:13:01', 0, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126275, 'finance', 'new_letter_of_guarantee', '保函管理-新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126279, 'account', 'destroy_account', '销户审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:15:40', '2023-11-21 14:15:40', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126281, 'finance', 'new_letter_guarantee_diminishing', '保函管理-费用递减审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126282, 'finance', 'new_letter_cost_registration', '保函管理-费用登记审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126283, 'finance', 'new_letter_deferred_registration', '保函管理-延期登记审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126284, 'finance', 'new_letter_of_guarantee_stop', '保函管理-终止审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126304, 'finance', 'inner_finance', '往来审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, '{\"en_us\":\"loan_inter_approve\",\"zh_cn\":\"往来审批\"}', 28, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126305, 'payment', 'account_trans_change', '银行流水变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"银行流水变更审批\"}', 20, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126306, 'finance', 'new_guarantee_contract', '担保合同-新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126307, 'finance', 'new_guarantee_renewal', '担保合同-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126308, 'finance', 'new_guarantee_stop', '担保合同-终止审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:14:58', '2023-11-21 14:14:58', 1, 0, NULL, NULL, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126309, 'bill', 'bill_discount_apply', '票据贴现', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:16:27', '2023-11-21 14:17:26', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126310, 'accounting_center', 'ras_subject_detail_recon_recall', '科目明细对账撤回审批*', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:17:25', '2023-11-21 14:17:25', 0, 0, '{\"en_us\":\"Account details reconciliation withdrawal approval\",\"zh_cn\":\"科目明细对账撤回审批*\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126311, 'accounting_center', 'ras_subject_detail_check', '科目明细对账审批*', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:17:25', '2023-11-21 14:17:25', 0, 0, '{\"en_us\":\"Account Detail Reconciliation examine and approve\",\"zh_cn\":\"科目明细对账审批*\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126312, 'accounting_center', 'ras_balance_adjustment', '余额调节表审批*', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:17:25', '2023-11-21 14:17:25', 0, 0, '{\"en_us\":\"Balance Reconciliation examine and approve\",\"zh_cn\":\"余额调节表审批*\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126313, 'bill', 'bill_endorse_apply_batch', '背书审批批量', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:17:25', '2023-11-21 14:19:11', 0, 0, '{\"en_us\":\"Endorsement Approval_Batch\",\"zh_cn\":\"背书审批批量\"}', 2, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126314, 'system', 'account_auth', '账户授权审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:23', '2023-11-21 14:20:23', 0, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126315, 'finance', 'new_issue_declaration_submit', '发行申报-新增审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:23', '2023-11-21 14:20:23', 1, 0, NULL, 23, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126316, 'finance', 'new_issue_contract', '合同登记新增', '{\"org\": [{\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}]}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:23', '2023-11-21 14:20:23', 1, 0, NULL, 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126317, 'payment', 'batch_reauthorization', '批量支付重新授权', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126318, 'payment', 'salary_reauthorization', '工资代发重新授权', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126319, 'payment', 'agent_batch_reauthorization', '代理批量支付重新授权', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126320, 'payment', 'agent_salary_reauthorization', '代理工资代发重新授权', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126321, 'finance', 'new_issue_declaration_change', '发行申报-变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 23, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126322, 'finance', 'new_issue_declaration_renewal', '发行申报-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 23, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126323, 'finance', 'new_issue_renewal', '合同登记-续期审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126324, 'finance', 'new_issue_change', '合同登记-变更审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg,applyOrg,payOrg\"}', '2023-11-21 14:20:40', '2023-11-21 14:20:40', 1, 0, NULL, 1, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126325, 'account', 'offline_account_flow_approval', '离线户流水审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:20:51', '2023-11-21 14:20:51', 0, 0, '{\"en_us\":\"Offline account flow approval\",\"zh_cn\":\"离线户流水审批\"}', 0, 0);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126326, 'account', 'new_open_account', '新账户审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:21:03', '2023-11-21 14:21:03', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"新账户审批\"}', 2, 10001);
INSERT INTO `sys_flow` (`id`, `category`, `code`, `name`, `fetch_field_definition_json`, `default_fetch_field_json`, `create_time`, `update_time`, `status`, `is_deleted`, `i18n_json`, `sort`, `parent_id`) VALUES (1647862228147126327, 'account', 'new_destroy_account', '新销户审批', '{\"org\": {\"userOrg\": \"用户所在组织\",\"applyOrg\": \"申请组织\",\"payOrg\": \"付款组织\"}}', '{\"org\": \"userOrg\"}', '2023-11-21 14:21:03', '2023-11-21 14:21:03', 1, 0, '{\"en_us\":\"\",\"zh_cn\":\"新销户审批\"}', NULL, 1647862228147126279);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
